compile: helloWorld.c
	# gcc -o mergeSort mergeSort.c -lm -g -O3 -lpthread
	# gcc -o bubbleSort bubbleSort.c -lm -g -O3 -lpthread
	# gcc -o oets oets.c -lm -g -O3 -lpthread
	gcc -o sort5 sort5.c -lm -g -O3 -lpthread

clean:
	rm mergeSort